sudo: required
services: 
  - docker

before_install:
  - docker build -t pheetah/docker-cicd-example -f Dockerfile.dev .

script: 
  - docker run -e CI=true pheetah/docker-cicd-example npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-example-1"
  env: "Dockerexample1-env"
  bucket_name: "elasticbeanstalk-us-east-1-338790333618"
  bucket_path: "docker-example-1"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"