sudo: required
services: 
  - docker

before_install:
  - docker build -t pheetah/docker-cicd-example -f Dockerfile.dev .

script: 
  - docker run -e CI=true pheetah/docker-cicd-example npm run test -- --coverage