sudo: required
services: 
  - docker

before_install:
  - docker build -t pheetah/docker-CICD-example -f Dockerfile.dev .

script: 
  - docker run pheetah/docker-CICD-example npm run test -- --coverage